---
- name: Update APT packages
  apt:
    update_cache: "yes"
    cache_valid_time: "3600"
    upgrade: full

- name: Install required packages
  apt:
    state: present
    name:
      - gcc
      - acl
      - nginx
      - certbot
      - postgresql
      - postgresql-client
      - libpq-dev
      - libpq5
      - python3-pip
      - python3-psycopg2
      - python3-certbot-nginx
      - python3-venv
      - python3-dev

- name: Remove default nginx config
  file:
    name: /etc/nginx/sites-enabled/default
    state: absent
  notify: Reload nginx

- name: Ensure journald drop-in directory exists
  file:
    path: /etc/systemd/journald.conf.d
    state: directory

- name: Configure journald log rotation
  template:
    src: journald.conf.j2
    dest: /etc/systemd/journald.conf.d/retention.conf
  notify: Restart journald

- name: Vacuum old logs
  command: journalctl --vacuum-time=1month
  changed_when: false
